#!/bin/bash
# AI/ML Landing Zone - Remote State Backend Setup
# This script ensures Terraform remote state backend exists and is configured
# It is idempotent and safe to run multiple times

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../default"
RESOURCE_GROUP="tfstate-rg-aiml-lz"
CONTAINER_NAME="tfstate"
STATE_KEY="aiml-lz-default.tfstate"
LOCATION="${AZURE_LOCATION:-eastus2}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔍 Checking Terraform remote state backend...${NC}"

# Check if we're authenticated
if ! az account show >/dev/null 2>&1; then
    echo -e "${RED}❌ Error: Not authenticated with Azure CLI${NC}"
    echo "   Please run: az login"
    exit 1
fi

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
echo -e "${GREEN}✅ Authenticated${NC} (Subscription: $SUBSCRIPTION_ID)"

# Check if resource group exists
if az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Resource group exists:${NC} $RESOURCE_GROUP"
    
    # Find existing storage account in the resource group
    STORAGE_ACCOUNT=$(az storage account list \
        --resource-group "$RESOURCE_GROUP" \
        --query "[?starts_with(name, 'tfstate')].name | [0]" \
        -o tsv)
    
    if [ -z "$STORAGE_ACCOUNT" ]; then
        echo -e "${YELLOW}⚠️  No storage account found in resource group${NC}"
        CREATE_STORAGE=true
    else
        echo -e "${GREEN}✅ Storage account exists:${NC} $STORAGE_ACCOUNT"
        CREATE_STORAGE=false
        
        # Verify container exists
        if az storage container show \
            --name "$CONTAINER_NAME" \
            --account-name "$STORAGE_ACCOUNT" \
            --auth-mode login >/dev/null 2>&1; then
            echo -e "${GREEN}✅ Container exists:${NC} $CONTAINER_NAME"
        else
            echo -e "${YELLOW}⚠️  Creating container...${NC}"
            az storage container create \
                --name "$CONTAINER_NAME" \
                --account-name "$STORAGE_ACCOUNT" \
                --auth-mode login >/dev/null
            echo -e "${GREEN}✅ Container created${NC}"
        fi
    fi
else
    echo -e "${YELLOW}⚠️  Resource group does not exist${NC}"
    CREATE_STORAGE=true
fi

# Create storage account if needed
if [ "$CREATE_STORAGE" = true ]; then
    echo -e "${BLUE}📦 Creating remote state storage...${NC}"
    
    # Create resource group
    echo "   Creating resource group..."
    az group create \
        --name "$RESOURCE_GROUP" \
        --location "$LOCATION" \
        --output none
    
    # Generate unique storage account name
    STORAGE_ACCOUNT="tfstate$(openssl rand -hex 4)"
    
    # Create storage account with RBAC-only access
    echo "   Creating storage account: $STORAGE_ACCOUNT"
    az storage account create \
        --name "$STORAGE_ACCOUNT" \
        --resource-group "$RESOURCE_GROUP" \
        --location "$LOCATION" \
        --sku Standard_LRS \
        --encryption-services blob \
        --allow-blob-public-access false \
        --allow-shared-key-access false \
        --output none
    
    # Create container
    echo "   Creating container: $CONTAINER_NAME"
    az storage container create \
        --name "$CONTAINER_NAME" \
        --account-name "$STORAGE_ACCOUNT" \
        --auth-mode login \
        --output none
    
    # Assign RBAC permissions to current user
    echo "   Assigning Storage Blob Data Contributor role..."
    CURRENT_USER=$(az ad signed-in-user show --query id -o tsv)
    az role assignment create \
        --role "Storage Blob Data Contributor" \
        --assignee "$CURRENT_USER" \
        --scope "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$STORAGE_ACCOUNT" \
        --output none 2>/dev/null || echo "   (Role may already be assigned)"
    
    echo -e "${GREEN}✅ Remote state storage created${NC}"
fi

# Create backend configuration file
BACKEND_CONFIG_FILE="$TERRAFORM_DIR/backend.tfvars"

cat > "$BACKEND_CONFIG_FILE" << EOF
# Auto-generated by ensure-remote-state.sh
# Do not edit manually - this file is regenerated on each azd provision
resource_group_name  = "$RESOURCE_GROUP"
storage_account_name = "$STORAGE_ACCOUNT"
container_name       = "$CONTAINER_NAME"
key                  = "$STATE_KEY"
use_azuread_auth     = true
EOF

echo -e "${GREEN}✅ Backend configuration file created${NC}"

# Ensure main.tf has the empty backend block
if ! grep -q 'backend "azurerm"' "$TERRAFORM_DIR/main.tf"; then
    echo -e "${YELLOW}⚠️  Adding backend block to main.tf...${NC}"
    # Insert empty backend block after required_providers
    awk '
        /^  }$/ && in_providers {
            print
            print ""
            print "  # Backend configuration is managed by ensure-remote-state.sh"
            print "  # Configuration is passed via backend config file or terraform init parameters"
            print "  backend \"azurerm\" {}"
            in_providers=0
            next
        }
        /required_providers/ { in_providers=1 }
        {print}
    ' "$TERRAFORM_DIR/main.tf" > "$TERRAFORM_DIR/main.tf.tmp"
    mv "$TERRAFORM_DIR/main.tf.tmp" "$TERRAFORM_DIR/main.tf"
    echo -e "${GREEN}✅ Backend block added${NC}"
fi

echo ""
echo -e "${GREEN}✅ Remote state backend ready${NC}"
echo ""
echo "Backend configuration:"
echo "  Resource Group:  $RESOURCE_GROUP"
echo "  Storage Account: $STORAGE_ACCOUNT"
echo "  Container:       $CONTAINER_NAME"
echo "  State File:      $STATE_KEY"
echo "  Authentication:  Entra ID (RBAC only)"
echo ""
